### ISSUE TITLE
Capture d'écran de l'interface actuelle

### ISSUE THREAD

**Issue by krijj** [hitmuri/vjpirate#1]
Yo @hitmuri, tu pourrais glisser quelques screenshot de l'interface actuelle dans le dossier créa-graphique ? Si possible avec 2/3 grilles et une boucle en train de jouer ?
Je peux plus lancer la version Mac sur mon ordi, elle n'est plus compatible.
J'ai retrouvé la créa de 2010.
Merci !

**Comment by hitmuri** [comment]
ok, il saute au  démarrage donc va falloir que je débug ça 
tu as pu récupérer les fichiers ?
quand tu les as il faut faire un npm install dans le dossier pour que ça récupère les bibliothèques three.js et osc.js

**Comment by hitmuri** [comment]
Voilou !


![vjp](https://user-images.githubusercontent.com/30658708/31852945-b3cb4bce-b680-11e7-9658-4ba239835e11.png)

**Comment by hitmuri** [comment]
ouh pardon, dans le dossier, j'ajoute ça

**Comment by krijj** [comment]
Super ! Je vais plancher sur une nouvelle interface.

**Comment by krijj** [comment]
Juste, est-ce que tu peux rajouter aussi avec les paramètres ouvert, et une avec les inputs ? Merci !

**Comment by hitmuri** [comment]
done !
