### ISSUE TITLE
Aide NPM

### ISSUE THREAD

**Issue by krijj** [hitmuri/vjpirate#2]
Salut,
Bon, j'ai tout installer sur ma bécane, j'ai fait npm install, tout est ok.
Maintenant quand je veux le voir dans le navigateur je dois faire un truc en plus ?
Parce que actuellement j'ai des erreurs et du coup rien ne fonctionne : 
![capture d ecran 2017-10-30 a 22 36 51](https://user-images.githubusercontent.com/7230605/32197058-25011910-bdc3-11e7-935a-b97fcc7c725d.png)

alors que si je fait "npm start" : il me lance l'appli NWJS et la ça marche : 
![capture d ecran 2017-10-30 a 22 41 36](https://user-images.githubusercontent.com/7230605/32197182-82fa1d50-bdc3-11e7-983c-fde78ddc89c0.png)

Je devrais pouvoir le faire marcher dans le navigateur non ?

j'ai eu des WARNING quand j'ai fait NPM install aussi : 
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.1.1 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.1.0 (node_modules/7zip-bin/node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.1.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN VjPirate@1.0.0 No description
npm WARN VjPirate@1.0.0 No repository field.
npm WARN VjPirate@1.0.0 license should be a valid SPDX license expression
macbookKrijj:vjpirate krijj$ 
```

**Comment by hitmuri** [comment]
Quel navigateur tu utilises ? J'ai l'impression que Webgl n'est pas activé ...

**Comment by krijj** [comment]
J'utilise Google Chrome à jour…

**Comment by hitmuri** [comment]
tu peux essayer sur firefox ou safari ?

**Comment by hitmuri** [comment]
tu peux vérifier si ça vient du navigateur : https://get.webgl.org/

**Comment by krijj** [comment]
Ok, merci, ça marche dans firefox et safari, je vais trouver l'astuce pour Chrome et au pire je le ferais sous FF

**Comment by krijj** [comment]
Bon, problème réglé : Chrome et Chromium ont blacklisté ma carte graphique car trop ancienne (2011)…
je peux encore désactiver l'option pour l'instant donc c'est bon.
